import { Injectable } from '@angular/core';
import { enfoque } from '../interfaces/enfoque';

@Injectable({
  providedIn: 'root'
})
export class EnfoqueService {

  enfoque: enfoque[] = [

        {
        "Fecha": "4/7/22",
        "IDdeCaso": 100965036,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101104067,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101258303,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101259233,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101383618,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101383618,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "NPS",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101383618,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "Satisfaccion Agente",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101383618,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101433107,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101433107,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 3,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101433107,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "NPS",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101433107,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "Satisfaccion Agente",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "9/7/22",
        "IDdeCaso": 101692427,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "10/7/22",
        "IDdeCaso": 101746802,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "10/7/22",
        "IDdeCaso": 101753578,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "NPS",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "10/7/22",
        "IDdeCaso": 101753578,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101876647,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101877694,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "NPS",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101884824,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 101997103,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 101997103,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "NPS",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 101997103,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "Satisfaccion Agente",
        "Respuesta": 2,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 101997103,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 2,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "13/7/22",
        "IDdeCaso": 102174788,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ARAUJO ELIO JAVIER",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101121878,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101131951,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101131951,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101253420,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101253420,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 2,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101273829,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101820484,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101866954,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101884377,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102009332,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102009332,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102016203,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "13/7/22",
        "IDdeCaso": 102150463,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "14/7/22",
        "IDdeCaso": 102336989,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "14/7/22",
        "IDdeCaso": 102343456,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "BATTAGLIA ROBERTO ESTEBAN",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "1/7/22",
        "IDdeCaso": 100662436,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101259840,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101399878,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101423375,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "9/7/22",
        "IDdeCaso": 101664036,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "9/7/22",
        "IDdeCaso": 101669612,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "9/7/22",
        "IDdeCaso": 101671807,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101886421,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "Satisfaccion Agente",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101886421,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102035345,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102035345,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "Satisfaccion Agente",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102035345,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102035345,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "NPS",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102035910,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102035910,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "CINI SANCHEZ DAVID JESUS",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101413227,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "ESCUDERO JAVIER ALEJANDRO",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101413227,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "ESCUDERO JAVIER ALEJANDRO",
        "Metrica": "NPS",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101413227,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "ESCUDERO JAVIER ALEJANDRO",
        "Metrica": "Satisfaccion Agente",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101558751,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "ESCUDERO JAVIER ALEJANDRO",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "2/7/22",
        "IDdeCaso": 100724705,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "2/7/22",
        "IDdeCaso": 100737931,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "NPS",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100952671,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100961567,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100961567,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101269799,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101439130,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101448809,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101562929,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101590806,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "14/7/22",
        "IDdeCaso": 102354314,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "MARQUEZ PIZARRO IRINA ALEJANDRA",
        "Metrica": "CES",
        "Respuesta": 3,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100979738,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101126358,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101156710,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101297354,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101458563,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101467575,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101471584,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101475149,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101898305,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "13/7/22",
        "IDdeCaso": 102185746,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "NPS",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "14/7/22",
        "IDdeCaso": 102331611,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "14/7/22",
        "IDdeCaso": 102335173,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "MESA MARIA SANDRA",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "2/7/22",
        "IDdeCaso": 100738166,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100950215,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100950215,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "NPS",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100975041,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 2,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100975041,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "NPS",
        "Respuesta": 3,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100975041,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100975041,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "Satisfaccion Agente",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101119009,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101119009,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101249423,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101263761,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101263761,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "NPS",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101263761,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101264551,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 3,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101266035,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101413234,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101441310,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 3,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101542681,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 3,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101553613,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 2,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101567898,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101580228,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102000708,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "13/7/22",
        "IDdeCaso": 102154598,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 3,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "13/7/22",
        "IDdeCaso": 102154598,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "NPS",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "13/7/22",
        "IDdeCaso": 102157550,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "13/7/22",
        "IDdeCaso": 102176824,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "14/7/22",
        "IDdeCaso": 102315630,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PAVEZ ISRAEL ANDRES",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "2/7/22",
        "IDdeCaso": 100754860,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "PENA NADIA SOLEDAD",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "2/7/22",
        "IDdeCaso": 100770580,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "PENA NADIA SOLEDAD",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "3/7/22",
        "IDdeCaso": 100817986,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "PENA NADIA SOLEDAD",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101132124,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "PENA NADIA SOLEDAD",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101254226,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "PENA NADIA SOLEDAD",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101254226,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "PENA NADIA SOLEDAD",
        "Metrica": "NPS",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101587567,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ROBLES LUCIANA ARACELLI",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101878850,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ROBLES LUCIANA ARACELLI",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101895915,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "ROBLES LUCIANA ARACELLI",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "4/7/22",
        "IDdeCaso": 100959420,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "NPS",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101110617,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101128584,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101415020,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101424514,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "9/7/22",
        "IDdeCaso": 101644907,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "9/7/22",
        "IDdeCaso": 101673140,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "9/7/22",
        "IDdeCaso": 101674039,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "10/7/22",
        "IDdeCaso": 101726822,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "NPS",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "10/7/22",
        "IDdeCaso": 101726822,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "10/7/22",
        "IDdeCaso": 101736176,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "NPS",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "10/7/22",
        "IDdeCaso": 101753659,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "NPS",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101877848,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101878864,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101893652,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102008629,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "NPS",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102008629,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102047256,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "TERUEL ELIZABETH BEATRIZ",
        "Metrica": "CES",
        "Respuesta": 5,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101127426,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VICENCIO LUCERO PRISCILA BELINDA",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101127426,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VICENCIO LUCERO PRISCILA BELINDA",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101127426,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VICENCIO LUCERO PRISCILA BELINDA",
        "Metrica": "NPS",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101422781,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VICENCIO LUCERO PRISCILA BELINDA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "10/7/22",
        "IDdeCaso": 101731087,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VICENCIO LUCERO PRISCILA BELINDA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101864940,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VICENCIO LUCERO PRISCILA BELINDA",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101873353,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VICENCIO LUCERO PRISCILA BELINDA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "11/7/22",
        "IDdeCaso": 101873353,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VICENCIO LUCERO PRISCILA BELINDA",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102027348,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "VICENCIO LUCERO PRISCILA BELINDA",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "13/7/22",
        "IDdeCaso": 102190204,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VICENCIO LUCERO PRISCILA BELINDA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "1/7/22",
        "IDdeCaso": 100649845,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "5/7/22",
        "IDdeCaso": 101109729,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101255619,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101262360,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "NPS",
        "Respuesta": 3,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101262360,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101270599,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101270599,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "6/7/22",
        "IDdeCaso": 101275634,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "7/7/22",
        "IDdeCaso": 101419074,
        "Grupo": "1ra. Línea",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101555825,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101555825,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "NPS",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101555825,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "Satisfaccion Agente",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101555825,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "Satisfaccion Tuenti",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101557430,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101568282,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "8/7/22",
        "IDdeCaso": 101570801,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "12/7/22",
        "IDdeCaso": 102045861,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "14/7/22",
        "IDdeCaso": 102303371,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 4,
        "Satisfaccion": "INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "14/7/22",
        "IDdeCaso": 102303371,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "NPS",
        "Respuesta": 6,
        "Satisfaccion": "NEUTRO",
        "NPS": "Detractor"
      },
      {
        "Fecha": "14/7/22",
        "IDdeCaso": 102334592,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "CES",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "NO APLICA"
      },
      {
        "Fecha": "14/7/22",
        "IDdeCaso": 102334592,
        "Grupo": "1ra Linea AMBA",
        "Canal": "External",
        "ASESOR": "VIDELA ANALIA VERONICA",
        "Metrica": "NPS",
        "Respuesta": 1,
        "Satisfaccion": "MUY INSATISFECHO",
        "NPS": "Detractor"
      }
  ];

  constructor() { }

  getEnfoque(){
   return this.enfoque.slice();
  }
}
